### ISSUE TITLE
Use an API ?

### ISSUE THREAD

**Issue by thdoteo** [Celivalg/getChronos#1]
Thank you for your work !

We should focus on using an API (there are two available apparently).
It would make the program more scalable and efficient (and solve the issue concerning the group selection).
But...

- http://webservices.chronos.epita.net/GetWeeks.aspx?auth=3piko&num=1&week=1&group=Trainee
I struggle to get the schedule for a certain week. This API should work because EpiLife uses it, according to its source code.

- http://v2.webservices.chronos.epita.net/api/v2/
Returns a 403 forbidden for any request.

Source:
- http://ctf.lse.epita.fr:52127/sources
- https://github.com/epita/chronos-ics

**Comment by Celivalg** [comment]
oh it's just me having fun screwing with js and chronos atm..
It's probably never gonna be a practical solution, however it's fun to see how much chronos is broken... so much unused stuff

**Comment by thdoteo** [comment]
Yeah but I was thinking you would take up the challenge :D!
Tell me if you succeed to use one API.

**Comment by Celivalg** [comment]
yeah well at least with  html and the js I got somewhere to start with, the first API looks...
btw the API Epilife V1 used is now apparently depreciated, I guess Epilife now use the v2 API

**Comment by thdoteo** [comment]
Where do you see that the first API is depreciated ? From what I saw it is still used in EpiLife code source.
I don't understand why the second doesn't work then...

**Comment by Celivalg** [comment]
first one I gave it no arguments (http://webservices.chronos.epita.net/GetWeeks.aspx) and everything was saying that this was depreciated, you sure it's epilife v2 and not the fisrt one?
Yeah I can't make the second one work either, back to parsing html I guess (btw if you look at chronos-ics's commits, they were parsing html too before :p )

**Comment by Celivalg** [comment]
also just some stuff you might want to see http://v2.webservices.chronos.epita.net/Help

**Comment by Celivalg** [comment]
I might be able to grab the old code from chronos-ics, but I don't want to, I want to figure it out myself :)

**Comment by thdoteo** [comment]
I will make sure by looking a second time. I've seen already this message but I don't trust it.
Yes chronos-ics used html parsing and then API v2... Weird.
Yes I have seen the documentation of the API v2 but http://v2.webservices.chronos.epita.net/api/v2/Room/GetRooms ....

**Comment by thdoteo** [comment]
Let's do Chronos API v3 then :D

**Comment by Celivalg** [comment]
yeaaah!

**Comment by Celivalg** [comment]
however their way of handling things makes it hard to manipulate what you want to get, basically the only input you can control in the GET request is the JSESSIONID and nothing else changes anything, and when that is some of my first time paying interest to some web stuff, it's hard

**Comment by Celivalg** [comment]
yeah if we get a response from their devs that might help me, all I wanted to do in the beginning was a small calendar for my statusbar with the next course :/

**Comment by thdoteo** [comment]
Yes but actually it's hard because the mean you are using is not done for getting info easily, it's a hack that's why API exists :D.
Same I have plenty of ideas to use Chronos data, like you.
I'll let you know if I get a solution.

**Comment by Celivalg** [comment]
oh I understand that, but isn't it the funniest way to do it? APIs are boring, even more when they don't work

**Comment by thdoteo** [comment]
Ok, needed a token to use api v2. Issue solved.
